export const assistantToolValues = [
  'property-line',
  'wall',
  'slab',
  'ceiling',
  'roof',
  'item',
  'zone',
  'window',
  'door',
  'cad-sketch',
  'cad-line',
  'cad-rectangle',
  'cad-circle',
  'cad-arc',
  'cad-polyline',
  'cad-coincident',
  'cad-horizontal-vertical',
  'cad-parallel-perpendicular',
  'cad-tangent',
  'cad-equal',
  'cad-dimension',
  'cad-import-step',
  'cad-extrude',
  'cad-revolve',
  'cad-boolean',
  'cad-fillet',
  'cad-chamfer',
  'cad-inspect',
] as const

export type AssistantToolPhase = 'site' | 'structure' | 'furnish' | 'cad'

// Keep this surface aligned with the tools the editor can actually mount or switch into today.
export const assistantToolPhaseMap: Record<
  (typeof assistantToolValues)[number],
  AssistantToolPhase
> = {
  'property-line': 'site',
  wall: 'structure',
  slab: 'structure',
  ceiling: 'structure',
  roof: 'structure',
  zone: 'structure',
  window: 'structure',
  door: 'structure',
  item: 'furnish',
  'cad-sketch': 'cad',
  'cad-line': 'cad',
  'cad-rectangle': 'cad',
  'cad-circle': 'cad',
  'cad-arc': 'cad',
  'cad-polyline': 'cad',
  'cad-coincident': 'cad',
  'cad-horizontal-vertical': 'cad',
  'cad-parallel-perpendicular': 'cad',
  'cad-tangent': 'cad',
  'cad-equal': 'cad',
  'cad-dimension': 'cad',
  'cad-import-step': 'cad',
  'cad-extrude': 'cad',
  'cad-revolve': 'cad',
  'cad-boolean': 'cad',
  'cad-fillet': 'cad',
  'cad-chamfer': 'cad',
  'cad-inspect': 'cad',
}
